### PR TITLE
Add a fedora redis server example.

### PR DESCRIPTION
**Pull request by mrunalp**
Dockerfile for redis server on Fedora.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Can you set this up to run as non-root?

**Comment by mrunalp** [comment]
@smarterclayton Changed to run as non-root.

**Comment by smarterclayton** [comment]
Needs volume for dir owned by redis, you'll need a single file in that dir in order to export permissions properly.

**Comment by mrunalp** [comment]
@smarterclayton Added the file and volume.

**Pull request merged**
