### PR TITLE
[WIP] Added self-contained Ruby builder image

### PR DESCRIPTION
**Pull request by mfojtik**
This patch allows users to use the `openshift/centos-ruby-builder` image as a self-contained Ruby applications builder. Developers don't need to install any additional tooling, all that is needed to be installed is the Docker image:

```
$ docker pull openshift/centos-ruby-builder
```

The basic building functionality this image provides allows developers to transform their source code into a fully functional Ruby application container. To get this done, users need to invoke:

```
$ docker run -v /path/to/source:/tmp/src openshift/centos-ruby-builder
--> Installing application source
---> Building your Ruby application from source
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Installing rack (1.5.2) 
Installing puma (2.8.1) with native extensions 
Installing rack-protection (1.5.2) 
Installing tilt (1.4.1) 
Installing sinatra (1.4.4) 
Using bundler (1.1.4) 
Your bundle is complete! It was installed into /opt/ruby/bundle
---> Build successful. Commit this image with: docker commit e708e53c4c05 ruby-app
```

This command mounts the local directory with sources into the builder image, where the sources are first installed into the 'application runtime' directory where as part of the building process the Bundler is used to install all dependencies from `Gemfile`.

The builder image Dockerfile specify `ENTRYPOINT ["/opt/ruby/bin/start"]`. This script initially points to the `build` script. After the `build` script finishes its job, then `/opt/ruby/bin/start` is replaced by the `run` command and the builder image exits to shell. This command will be used later to start the Ruby application server.  The last line of the `build` script is suggesting to developer to commit the resulting container (CID is provided):

```
$ docker commit e708e53c4c05 ruby-app
bb0079295518725a817bbf0d9400a400516c38571bb0fc3a77c1a17e6d91846a
```

The `docker commit` command, converts the container to a runnable application image. The `ENTRYPOINT` now points to the `run` command. To start the application, developer just needs to run:

```
$ docker run --rm -p 9292:9292 ruby-app
Puma starting in single mode...
* Version 2.8.1 (ruby 1.9.3-p448), codename: Sir Edmund Percival Hillary
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

The `docker` process itself is the parent of the `puma` process, so after pressing Ctrl-C, the puma shutdown and the container is stopped.

The builder image also provides a way to debug the application itself in a container, but also the builder itself. All you have to do is to append `--debug` at the end of command line. If you do, instead of 'build' you will be dropped into a bash right before the build. In case of `run`, you will be dropped into bash right before we execute the Ruby application server. Note that 'bash' requires pseudoterminal, so you will have to add the `-i -t` options to the `docker run` command.

### CODE REVIEW

**Comment by mfojtik** [comment]
@smarterclayton @pmorie I pushed the `mfojtik/centos-ruby-builder` image to Docker registry, so you can play with it.

I'm using this repo for Rack/Sinatra: https://github.com/mfojtik/sinatra-app-example
And this repo for the Rails 4: https://github.com/mfojtik/rails-app-example

**Comment by mfojtik** [comment]
@jwforres fyi ^^

**Comment by mfojtik** [comment]
Btw. to make this easy to use for Ruby developers, we can provide some nice rubygem, they can add to Rails app and it will provide something like:

```
rake docker:build
rake docker:run
```

**Comment by mfojtik** [comment]
@smarterclayton @pmorie @jwforres I squashed all commits and make it as a 'new' image instead of having it as a sub-folder in 'centos-ruby'.

Note: This commit will break the current STI workflow as this remove '/usr/bin/{prepare,run,*-artifacts}' files.

**Comment by smarterclayton** [comment]
I'm going to merge this so folks can test against a public image - once we're clear on a path we'll remove centos-ruby and move this into that path

**Pull request merged**
