### PR TITLE
Change haproxy port to 8080

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by mrunalp** [comment]
@pmorie Seems like the issue is somehow related to atomic. The image works fine on Fedora.

**Comment by pmorie** [comment]
mrunal, that jives with my own experience, this is an issue on the latest atomic box

**Comment by pmorie** [comment]
@cgwalters ^^

**Comment by mrunalp** [comment]
@cgwalters Applications aren't able to bind to port 80 in this container when running on latest atomic.

**Pull request closed without merging**
