### PR TITLE
convert images to basic platform images, not STI specific

### PR DESCRIPTION
**Pull request by bparees**
centos-ruby and centos-ruby2 provide a basic image that can assemble code (by running the prepare script) and run code (via the run script) if the user bind-mounts source in on run.  (for ruby 19 and 20 respectively)

centos-ruby-builder demonstrates an auto-executing image that will prepare and then switch to a default mode of run, again assuming source is bind-mounted in.

wildfly is just a basic image that contains/starts wildfly, and includes maven.

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton not sure this is 100% of what you wanted, let's discuss further if it's not.  I'm somewhat tempted to remove all the prepare/run scripts from all these images.

**Comment by smarterclayton** [comment]
Looks pretty good.  Is there anything else you'd yank?

**Comment by bparees** [comment]
like I said, i'd consider yanking the prepare/run scripts but i think they might be instructive to someone trying to use the images.

I also think centos-ruby-builder is perhaps out of place here since it's really a science experiment more than a useful image.

I didn't look at the other (non-STI-enabled) images.

**Comment by smarterclayton** [comment]
Nuke centos-ruby-builder then.

**Comment by bparees** [comment]
@smarterclayton 
ok we're down to "centos-ruby-selfcontained" which is a rename of centos-ruby-builder, plus merging in centos-ruby so it's no longer dependent on centos-ruby(which has been deleted).

I think i'm done so feel free to merge unless you have additional questions/comments

**Comment by bparees** [comment]
@mfojtik fyi.

**Comment by mfojtik** [comment]
:+1:

**Pull request merged**
